### PR TITLE
fix ServerConfig scheme was ignored in nacos server

### LINKED ISSUE #149: 生成读取配置的url时，未使用传入的scheme配置，导致无法使用https协议
生成读取配置的url时，未使用传入的scheme配置，导致无法使用https协议
https://github.com/nacos-group/nacos-sdk-go/blob/fb45465888781748568f906fe55137f718a31af7/common/nacos_server/nacos_server.go#L315

### PR DESCRIPTION
**Pull request by mark4z**
Fixes #149

### CODE REVIEW

File: clients/config_client/config_client_test.go [hunk 1]
```diff
@@ -154,7 +154,7 @@ func Test_SearchConfig(t *testing.T) {
 	})
 	assert.Nil(t, err)
 	assert.NotEmpty(t, configPage)
-	assert.NotEmpty(t, configPage.PageItems)
+	//assert.NotEmpty(t, configPage.PageItems)
```
Comment (sanxun0325) [inline clients/config_client/config_client_test.go]: this PR will affect ut? If so, please explain the reason, do not mark

File: common/nacos_server/nacos_server.go [hunk 2]
```diff
@@ -313,7 +305,7 @@ func injectSecurityInfo(server *NacosServer, param map[string]string) {
 }
 
 func getAddress(cfg constant.ServerConfig) string {
-	return cfg.IpAddr + ":" + strconv.Itoa(int(cfg.Port))
+	return cfg.Scheme + "://" + cfg.IpAddr + ":" + strconv.Itoa(int(cfg.Port))
```
Comment (sanxun0325) [inline common/nacos_server/nacos_server.go:308]: Can you add UT to this function

File: clients/nacos_client/nacos_client.go [hunk 3]
```diff
@@ -93,6 +93,9 @@ func (client *NacosClient) SetServerConfig(configs []constant.ServerConfig) (err
 		if len(configs[i].ContextPath) <= 0 {
 			configs[i].ContextPath = constant.DEFAULT_CONTEXT_PATH
 		}
+		if configs[i].Scheme == "" {
```
Comment (sanxun0325) [inline clients/nacos_client/nacos_client.go:96]: use len(configs[i].Scheme)<=0 ，keep the style consistent

Comment (mark4z) [reply clients/nacos_client/nacos_client.go:96]: okay, fine

File: common/nacos_server/nacos_server.go (hunk 2 above)
Comment (mark4z) [reply common/nacos_server/nacos_server.go:308]: ok

File: clients/config_client/config_client_test.go (hunk 1 above)
Comment (mark4z) [reply clients/config_client/config_client_test.go]: This test Fail because there are no matching config, i add one in console.nacos.io. and now i've revert it.

File: common/nacos_server/nacos_server_test.go [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+	"github.com/nacos-group/nacos-sdk-go/common/constant"
+	"github.com/stretchr/testify/assert"
+)
+
+func Test_getAddressWithScheme(t *testing.T) {
+	var serverConfigTest = constant.ServerConfig{
+		ContextPath: "/nacos",
+		Port:        80,
+		IpAddr:      "console.nacos.io",
+		Scheme:      "https",
```
Comment (mark4z) [inline common/nacos_server/nacos_server_test.go:31]: UT to this getAddress, because we have not nacos url with https, so ...

File: clients/config_client/config_client_test.go [hunk 5]
```diff
@@ -143,6 +159,25 @@ func Test_GetConfig(t *testing.T) {
 	assert.Equal(t, "hello world!222222", content)
 }
 
+func Test_GetConfigWithScheme(t *testing.T) {
```
Comment (sanxun0325) [inline clients/config_client/config_client_test.go:162]: This func is not necessary.

File: clients/config_client/config_client_test.go [hunk 6]
```diff
@@ -97,6 +97,22 @@ func cretateConfigClientTest() ConfigClient {
 	return client
 }
 
+func createConfigClientWithScheme() ConfigClient {
```
Comment (sanxun0325) [inline clients/config_client/config_client_test.go:100]: This func is not necessary.The default value of Scheme in the current PR is HTTP

**Review by sanxun0325 — APPROVED** [review]

File: common/nacos_server/nacos_server.go (hunk 2 above)
Comment (lzp0412) [inline common/nacos_server/nacos_server.go:308]: pls verify whether ipaddr starts with http:// or https://，some old user may config like this ‘http://console.nacos.io’

**Comment by lzp0412** [comment]
@mark4z can you modify the use document to explain this usage？

File: common/nacos_server/nacos_server.go (hunk 2 above)
Comment (mark4z) [reply common/nacos_server/nacos_server.go:308]: ok, i will

**Comment by mark4z** [comment]
> @mark4z can you modify the use document to explain this usage？

I will

**Comment by mark4z** [comment]
> @mark4z can you modify the use document to explain this usage？

Now document was update

**Comment by sanxun0325** [comment]
Nice work, looking forward to more contributions
